### ISSUE TITLE
google podcast and iTunes compatible

### ISSUE THREAD

**Issue by jariobr** [schulle4u/yellow-plugin-podcast#2]
@schulle4u @markseu 

The podcast plugin causes problems when publishing podcasts in Google Music Podcasts and iTunes podcasts, because it mixes the blog posts with podcasts posts, this plugin (yellow-plugin-podcastfeed) solves this problem.

https://github.com/jariobr/yellow-plugin-podcastfeed

**Comment by schulle4u** [comment]
Thank you, I'll look into it. To be honest I haven't tested iTunes and Google Podcast compatibility, their submitting rules are technically annoying in some points and I'm ignoring this audience for my own little projects. :) Most podcast clients simply omit articles without a media item. 

Want to give me a pull request?
